all:
	g++ -g -Wall -o Problem_02_MinPathSum Problem_02_MinPathSum.cpp
	g++ -g -Wall -o Problem_15_JumpGame Problem_15_JumpGame.cpp
	g++ -g -Wall -o Problem_16_LongestConsecutive Problem_16_LongestConsecutive.cpp


clean:
	rm Problem_02_MinPathSum Problem_15_JumpGame Problem_16_LongestConsecutive
