all:
	g++ -g -Wall -o Problem_01_PreInPosTraversal Problem_01_PreInPosTraversal.cpp
	g++ -g -Wall -o Problem_13_IsBalancedTree Problem_13_IsBalancedTree.cpp

clean:
	rm -rf Problem_01_PreInPosTraversal Problem_13_IsBalancedTree
