all:
	g++ -g -Wall -o Problem_01_PreInPosTraversal Problem_01_PreInPosTraversal.cpp
	g++ -g -Wall -o Problem_13_IsBalancedTree Problem_13_IsBalancedTree.cpp
	g++ -g -Wall -o Problem_16_SortedArrayToBalancedBST Problem_16_SortedArrayToBalancedBST.cpp

clean:
	rm -rf Problem_01_PreInPosTraversal Problem_13_IsBalancedTree \
		Problem_16_SortedArrayToBalancedBST
