all:
	g++ -g -Wall -o Problem_01_PrintCommonPart Problem_01_PrintCommonPart.cpp
	g++ -g -Wall -o Problem_02_RemoveLastKthNode Problem_02_RemoveLastKthNode.cpp
	g++ -g -Wall -o Problem_03_RemoveNodeByRatio Problem_03_RemoveNodeByRatio.cpp
	g++ -g -Wall -o Problem_04_ReverseList Problem_04_ReverseList.cpp
	g++ -g -Wall -o Problem_05_ReversePartList Problem_05_ReversePartList.cpp
	g++ -g -Wall -o Problem_07_IsPalindromeList Problem_07_IsPalindromeList.cpp
	g++ -g -Wall -o Problem_08_SmallerEqualBigger Problem_08_SmallerEqualBigger.cpp
	g++ -g -Wall -o Problem_09_CopyListWithRandom Problem_09_CopyListWithRandom.cpp
	g++ -g -Wall -o Problem_10_AddTwoLinkedLists Problem_10_AddTwoLinkedLists.cpp


clean:
	rm -rf Problem_01_PrintCommonPart Problem_02_RemoveLastKthNode Problem_03_RemoveNodeByRatio Problem_04_ReverseList \
		Problem_05_ReversePartList Problem_07_IsPalindromeList Problem_08_SmallerEqualBigger \
		Problem_09_CopyListWithRandom Problem_10_AddTwoLinkedLists
