all:
	g++ -g -Wall -o Problem_01_GetMinStack Problem_01_GetMinStack.cpp
	g++ -g -Wall -o Problem_03_ReverseStackUsingRecursive Problem_03_ReverseStackUsingRecursive.cpp
	g++ -g -Wall -o Problem_05_StackSortStack Problem_05_StackSortStack.cpp
	g++ -g -Wall -o Problem_07_SlidingWindowMaxArray Problem_07_SlidingWindowMaxArray.cpp


clean:
	rm Problem_01_GetMinStack Problem_03_ReverseStackUsingRecursive Problem_05_StackSortStack \
		Problem_07_SlidingWindowMaxArray
