all:
	g++ -g -Wall -o Problem_01_PrintMatrixSpiralOrder Problem_01_PrintMatrixSpiralOrder.cpp
	g++ -g -Wall -o Problem_02_RotateMatrix Problem_02_RotateMatrix.cpp
	g++ -g -Wall -o Problem_05_MinLengthForSort Problem_05_MinLengthForSort.cpp
	g++ -g -Wall -o Problem_06_FindKMajority Problem_06_FindKMajority.cpp


clean:
	rm -rf Problem_01_PrintMatrixSpiralOrder Problem_02_RotateMatrix Problem_05_MinLengthForSort \
		Problem_06_FindKMajority
