all:
	g++ -g -Wall -o Problem_01_PrintMatrixSpiralOrder Problem_01_PrintMatrixSpiralOrder.cpp
	g++ -g -Wall -o Problem_05_MinLengthForSort Problem_05_MinLengthForSort.cpp


clean:
	rm -rf Problem_01_PrintMatrixSpiralOrder Problem_05_MinLengthForSort
