all:
	g++ -g -Wall -o Problem_01_SwapWithoutTmp Problem_01_SwapWithoutTmp.cpp
	g++ -g -Wall -o Problem_02_GetMax Problem_02_GetMax.cpp
	g++ -g -Wall -o Problem_04_NumberOf1 Problem_04_NumberOf1.cpp
	g++ -g -Wall -o Problem_05_EvenTimesOddTimes Problem_05_EvenTimesOddTimes.cpp
	g++ -g -Wall -o Problem_06_KTimesOneTime Problem_06_KTimesOneTime.cpp

clean:
	rm Problem_01_SwapWithoutTmp Problem_02_GetMax Problem_04_NumberOf1 \
		Problem_05_EvenTimesOddTimes Problem_06_KTimesOneTime
