all:
	g++ -g -Wall -o Problem_01_IsDeformation Problem_01_IsDeformation.cpp
	g++ -g -Wall -o Problem_04_IsRotation  Problem_04_IsRotation.cpp


clean:
	rm -rf Problem_01_IsDeformation Problem_04_IsRotation
