all:
	g++ -g -Wall -o Problem_01_IsDeformation Problem_01_IsDeformation.cpp
	g++ -g -Wall -o Problem_03_RemoveKZeros  Problem_03_RemoveKZeros.cpp
	g++ -g -Wall -o Problem_04_IsRotation  Problem_04_IsRotation.cpp
	g++ -g -Wall -o Problem_10_ModifyAndReplace  Problem_10_ModifyAndReplace.cpp


clean:
	rm -rf Problem_01_IsDeformation Problem_04_IsRotation Problem_03_RemoveKZeros Problem_10_ModifyAndReplace
