all:
	g++ -g -Wall -o Problem_01_IsDeformation Problem_01_IsDeformation.cpp
	g++ -g -Wall -o Problem_03_RemoveKZeros  Problem_03_RemoveKZeros.cpp
	g++ -g -Wall -o Problem_04_IsRotation  Problem_04_IsRotation.cpp
	g++ -g -Wall -o Problem_07_ConvertStringToCount  Problem_07_ConvertStringToCount.cpp
	g++ -g -Wall -o Problem_10_ModifyAndReplace  Problem_10_ModifyAndReplace.cpp
	g++ -g -Wall -o Problem_18_LongestNoRepeatSubstring Problem_18_LongestNoRepeatSubstring.cpp


clean:
	rm -rf Problem_01_IsDeformation Problem_04_IsRotation Problem_03_RemoveKZeros Problem_10_ModifyAndReplace \
		Problem_07_ConvertStringToCount Problem_18_LongestNoRepeatSubstring
